export const SET_PRODUCTS = 'products/setProducts'
export const SET_ACTIVE_PRODUCT = 'products/setActiveProduct'
export const SET_PRODUCT = 'products/setProduct'
export const SET_UPDATED_PRODUCT = 'products/setUpdatedProduct'
export const SET_IS_FETCHING = 'products/setIsFetching'
