export const SET_PRODUCTS = 'products/setProducts'
export const SET_DELETE_PRODUCT = 'products/setDeleteProduct'
export const SET_PRODUCT = 'products/setProduct'
export const SET_UPDATED_PRODUCT = 'products/setUpdatedProduct'
export const SET_IS_FETCHING = 'products/setIsFetching'
